language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

sudo: false

before_script:
- composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit tests

notifications:
  email:
    on_failure: change
